<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { api, type RunEvidenceData } from '../api'
import RunEvidence from './RunEvidence.vue'
import RaceCycle from './RaceCycle.vue'
import type { RaceCycleData } from '../api'
type Longest={id:string;date:string;title:string;distance_m:number;duration_seconds:number;effort:number|null;pain_notes:string}
type Step={id:string;title:string;state:'needs_info'|'needs_review'|'recorded';detail:string;action:'feedback'|'settings'|'calendar'|'records';evidence_ids:string[]}
type Assessment={race_cycle:RaceCycleData;next_steps:{label:string;note:string;items:Step[]};as_of:string;window_start:string;facts_revision:number;goal:{date:string|null;duration_seconds:number|null;pace_seconds_per_km:number|null;feasibility:string};runs:{sport:string;count:number;distance_m:number;duration_seconds:number;missing_effort_count:number;longest:Longest|null;latest_evidence:RunEvidenceData|null;evidence_ids:string[]}[];weeks:{start:string;end:string;count:number;distance_m:number}[];strength:{completed:number;partial:number;skipped:number;duration_seconds:number;evidence_ids:string[]};feedback_count:number;limitations:string[];attention:string[]}
const props=defineProps<{refreshToken:number;today:string}>()
const emit=defineEmits<{navigate:[view:'settings'|'calendar'|'records'];feedback:[]}>()
const stepLabels={needs_info:'待补充',needs_review:'待核对',recorded:'已记录'}
const actionLabels={feedback:'填写身体反馈',settings:'打开个人设置',calendar:'核对训练日历',records:'打开训练记录'}
function act(step:Step){if(step.action==='feedback')emit('feedback');else emit('navigate',step.action)}
const state=ref<Assessment|null>(null),error=ref('')
const labels:Record<string,string>={road_run:'公路跑',trail_run:'越野跑',treadmill:'跑步机'}
function pace(seconds:number){return `${Math.floor(seconds/60)}′${String(seconds%60).padStart(2,'0')}″ / km`}
async function load(){error.value='';try{state.value=await api<Assessment>('/assessment')}catch(e){state.value=null;error.value=(e as Error).message}}
onMounted(load);watch(()=>[props.refreshToken,props.today],load)
</script>
<template><section class="card assessment"><div class="sectionhead"><div><h2>初始评估 · 先看依据</h2><p class="tiny muted">已保存事实的计算摘要；训练基础见下方周期评估，目标可行性需要专项依据。</p></div><span class="badge">本地计算</span></div><p v-if="error" role="alert">{{error}}</p><template v-if="state"><p class="tiny muted">{{state.window_start}} — {{state.as_of}} · 最近 28 天 · 事实修订 {{state.facts_revision}}</p><div class="assessment-steps"><div class="sectionhead"><h3>下一步，从这里开始</h3><span class="badge">{{state.next_steps.label}}</span></div><p class="tiny muted">{{state.next_steps.note}}</p><div v-for="step in state.next_steps.items" :key="step.id" class="assessment-step"><div><div class="row"><b>{{step.title}}</b><span class="badge" :class="{pending:step.state!=='recorded'}">{{stepLabels[step.state]}}</span></div><p class="tiny muted">{{step.detail}}</p></div><button class="btn" @click="act(step)">{{actionLabels[step.action]}} →</button></div></div><RaceCycle :cycle="state.race_cycle" @settings="emit('navigate','settings')"/><div class="assessment-goal"><b>半马目标配速：{{state.goal.pace_seconds_per_km===null?'尚未设置':pace(state.goal.pace_seconds_per_km)}}</b><p class="tiny muted">{{state.goal.feasibility}}。不会用目标配速直接安排训练。</p></div><div class="assessment-grid"><div v-for="r in state.runs" :key="r.sport" class="assessment-box"><h3>{{labels[r.sport]}}</h3><p><b>{{r.count}}</b> 条 · {{(r.distance_m/1000).toFixed(2)}} 公里</p><p class="tiny muted">已记录 {{Math.round(r.duration_seconds/60)}} 分钟 · {{r.missing_effort_count}} 条缺少主观用力</p><details v-if="r.longest"><summary class="tiny">查看最长一次的依据</summary><p class="tiny">{{r.longest.date}} · {{r.longest.title}}<br>{{(r.longest.distance_m/1000).toFixed(2)}} 公里 / {{Math.round(r.longest.duration_seconds/60)}} 分钟<br>主观用力：{{r.longest.effort??'未知'}}<br>疼痛备注：{{r.longest.pain_notes||'未填写；不代表无痛'}}</p><p class="tiny muted evidence-id">记录 ID：{{r.longest.id}}</p></details><RunEvidence v-if="r.latest_evidence" :evidence="r.latest_evidence"/></div><div class="assessment-box"><h3>身体反馈</h3><p class="tiny muted">身体反馈 {{state.feedback_count}} 条</p></div></div><details class="assessment-detail"><summary>查看四段七天记录与评估边界</summary><p v-for="w in state.weeks" :key="w.start" class="tiny">{{w.start}} — {{w.end}}：{{w.count}} 条跑步 / {{(w.distance_m/1000).toFixed(2)}} 公里</p><p v-for="l in state.limitations" :key="l" class="tiny muted">{{l}}</p></details><div v-if="state.attention.length" class="assessment-attention"><b>下一步先核对身体状态</b><p v-for="a in state.attention" :key="a" class="tiny">{{a}}</p></div><p class="tiny muted">可先补录已有跑步与身体反馈；当前信息不足时保留未知，不需要为了填满数据做全力测试。</p></template></section></template>
<style scoped>
.assessment-steps{margin:20px 0}.assessment-step{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid #e5e8df}.assessment-step>div{min-width:0;flex:1}.assessment-step .row{justify-content:flex-start;flex-wrap:wrap;gap:12px}.assessment-step .btn{flex-shrink:0}.assessment-step p{margin-top:8px}.assessment-step .pending{background:#fbf3e5}.assessment{margin:24px 0}.assessment .sectionhead{gap:12px;align-items:flex-start}.assessment .sectionhead p{margin-top:8px}.assessment-goal{background:#f3f5ef;padding:16px;border-radius:12px;margin:16px 0}.assessment-grid{display:grid;align-items:start;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.assessment-box{border:1px solid #e5e8df;border-radius:12px;padding:16px;min-width:0}.assessment-box p,.assessment-detail p,.assessment-attention p{margin:10px 0}.assessment-detail{margin:18px 0}.assessment-attention{background:#fbf3e5;padding:16px;border-radius:12px;margin-bottom:16px}.evidence-id{overflow-wrap:anywhere}@media(max-width:550px){.assessment-step{align-items:flex-start;flex-direction:column}.assessment-step .btn{width:100%}.assessment-grid{grid-template-columns:1fr}.assessment .sectionhead{flex-wrap:wrap}}
</style>
