<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { api, json, type AIUsage } from '../api'
const props=defineProps<{refreshToken:number}>(),emit=defineEmits<{feedback:[]}>()
type Turn={id:string;request_id:string;message:string;state:string;provider:string;is_mock:boolean;facts_revision:number;context_stale:boolean;created_at:string;error:string;reply?:string;questions?:string[];uncertainties?:string[];evidence_ids?:string[]}
const turns=ref<Turn[]>([]),ai=ref<AIUsage|null>(null),message=ref(''),requestId=ref<string|null>(null),busy=ref(false),error=ref(''),consent=ref(false)
async function load(){const [history,usage]=await Promise.all([api<{turns:Turn[]}>('/coach/messages'),api<AIUsage>('/ai/usage')]);turns.value=history.turns;ai.value=usage}
async function refresh(){try{await load()}catch(e){error.value=(e as Error).message}}
async function send(){if(!message.value.trim()||busy.value)return;busy.value=true;error.value='';requestId.value||=crypto.randomUUID();try{await api('/coach/messages',json('POST',{message:message.value,request_id:requestId.value,allow_external_ai:consent.value}));message.value='';requestId.value=null;await load()}catch(e){error.value=(e as Error).message;await refresh()}finally{busy.value=false}}
function retry(t:Turn){message.value=t.message;requestId.value=null;error.value='';consent.value=false}
watch(message,()=>{if(!busy.value)requestId.value=null})
watch(()=>props.refreshToken,refresh)
onMounted(refresh)
</script>
<template><section class="card panelwide coach-chat"><div class="sectionhead"><div><h2>AI 跑步训练教练</h2><p class="tiny muted">解释记录、核对变化、协调跑步与恢复</p></div><span class="badge">{{ai?.provider==='deepseek'?'DeepSeek · 待真实验收':'模拟教练'}}</span></div><p class="evidence-note">{{ai?.provider==='deepseek'?'已接入对话适配器，回答仅供核对，不直接生成或更新训练安排。':'当前为固定流程回复，没有调用 DeepSeek。'}} 不自称真人教练或医疗人员，不诊断伤痛、不承诺比赛成绩。聊天记录会保存在本机。</p><p class="tiny muted">聊天中的新疼痛、酸胀或疾病尚未成为训练事实，请先保存身体反馈；调整安排仍需核对并确认下方跑步草稿。</p><div class="actions"><button class="btn" @click="emit('feedback')">保存身体反馈</button><button class="btn" :disabled="busy" @click="refresh">刷新回复状态</button></div><p v-if="error" class="error" role="alert">{{error}}</p><div v-if="!turns.length" class="empty">可以从“今天跑完感觉有点累，后续跑步课程该如何调整？”开始聊。</div><article v-for="t in turns" :key="t.id" class="coach-exchange"><div class="chat user"><span class="tiny muted">你 · {{new Date(t.created_at).toLocaleString('zh-CN')}}</span><p>{{t.message}}</p></div><div class="chat"><span class="badge">{{t.is_mock?'模拟回复':'AI 回复'}} · {{t.state==='succeeded'?'已保存':t.state==='processing'?'处理中':t.state==='interrupted'?'结果未知':'未完成'}}</span><p v-if="t.context_stale" class="evidence-note">此回复依据的资料已变化，请按最新反馈重新评估。</p><p v-if="t.state==='succeeded'" class="coach-reply">{{t.reply}}</p><p v-else class="tiny">{{t.error||'正在处理。可以稍后刷新状态；重复提交同一请求不会额外调用。'}}</p><ul v-if="t.questions?.length"><li v-for="q in t.questions" :key="q">{{q}}</li></ul><p v-for="u in t.uncertainties" :key="u" class="tiny muted">{{u}}</p><p class="tiny muted">基于事实修订 {{t.facts_revision}} · 未修改计划</p><button v-if="['failed','interrupted'].includes(t.state)" class="textbtn" @click="retry(t)">作为新问题重试（真实模式可能另计费用） →</button></div></article><p v-if="turns.length===50" class="tiny muted">显示最近 50 次提问；模型上下文最多包含最近 6 次成功问答。</p><label v-if="ai?.provider==='deepseek'" class="privacy-check"><input v-model="consent" type="checkbox">同意将本次问题、最近最多 6 次成功问答、已保存档案（含身体情况及医生限制）、近期最多 10 次跑步（含已确认详细指标）／3 次身体反馈、当前计划与七天日程发送至 DeepSeek。不会主动读取原图、路线、账号或密码；问题和记录备注会发送，请勿写入密钥或密码。</label><form class="composer" @submit.prevent="send"><textarea v-model="message" aria-label="教练消息" placeholder="今天跑完感觉……" maxlength="4000" :disabled="busy"></textarea><button class="btn primary" :disabled="busy||!message.trim()||(ai?.provider==='deepseek'&&!consent)">{{busy?'回复中…':'发送 ↗'}}</button></form></section></template>
