<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { api,json,type AbilityData,type PlanState,type Profile,type Proposal,type Plan,type Exercise,type AIUsage,type PlanItem,type WeatherData } from '../api'
const props=defineProps<{today:string;refreshToken:number}>(),emit=defineEmits<{changed:[]}>()
const state=ref<PlanState|null>(null),ability=ref<AbilityData|null>(null),profile=ref<Profile|null>(null),ai=ref<AIUsage|null>(null),versions=ref<Plan[]>([]),history=ref<Plan|null>(null),exercises=ref<Exercise[]>([]),selected=ref<Proposal|null>(null)
const weather=ref<WeatherData|null>(null),includeWeather=ref(false),avoidRain=ref(false)
const busy=ref(false),error=ref(''),notice=ref(''),external=ref(false),controlled=ref(false),start=ref(props.today),preserve=ref(true)
const slots=ref(Array.from({length:7},(_,weekday)=>({weekday,enabled:false,duration_minutes:30})))
const dayNames=['周一','周二','周三','周四','周五','周六','周日']
const phases:Record<string,string>={foundation:'基础适应',build:'持续训练',consolidate:'巩固与恢复',taper:'赛前减量',race_week:'比赛周',post_race:'赛后恢复'}
const statusLabels={insufficient:'资料不足',limited:'初步训练基础',established:'已有连续训练依据'}
const candidates=computed(()=>state.value?.proposals.filter(p=>p.scope==='cycle')||[])
const current=computed(()=>state.value?.plan?.scope==='cycle'?state.value.plan:null)
const shown=computed<Proposal|Plan|null>(()=>selected.value||history.value||current.value)
const proposalLabels:Record<string,string>={pending:'待确认',applied:'已应用',expired:'已失效',rejected:'已拒绝'}
const types={run:'跑步',strength:'力量',recovery:'恢复 / 待核对'}
function sessions(begin:string,end:string){return shown.value?.sessions.filter(s=>s.type!=='strength'&&begin<=s.date&&s.date<=end)||[]}
function total(items:PlanItem[],type:string){return items.filter(s=>s.type===type).reduce((n,s)=>n+s.duration_minutes,0)}
async function load(){
 const [a,s,p,e,u,v,w]=await Promise.all([api<{ability:AbilityData}>('/assessment'),api<PlanState>('/plans/current'),api<Profile>('/profile'),api<Exercise[]>('/exercises'),api<AIUsage>('/ai/usage'),api<Plan[]>('/plans/versions'),api<WeatherData>('/weather')])
 weather.value=w;ability.value=a.ability;state.value=s;versions.value=v.filter(v=>v.scope==='cycle');profile.value=p;exercises.value=e;ai.value=u
 if(selected.value)selected.value=s.proposals.find(p=>p.id===selected.value?.id)||null
}
async function schedule(){if(!state.value)return;busy.value=true;error.value='';try{await api('/cycle-schedule',json('PUT',{start_date:start.value,slots:slots.value.filter(s=>s.enabled).map(s=>({weekday:s.weekday,duration_minutes:s.duration_minutes})),preserve_existing:preserve.value,expected_facts_revision:state.value.facts_revision}));await load();notice.value='周期日程已保存，正式计划尚未更新；可以在日历修改任意一天。';emit('changed')}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function generate(){if(!state.value)return;busy.value=true;error.value='';try{selected.value=await api<Proposal>('/cycle-proposals',json('POST',{start_date:start.value,allow_external_ai:external.value,allow_controlled_work:controlled.value,include_weather:includeWeather.value,avoid_rain:includeWeather.value&&avoidRain.value,expected_weather_revision:includeWeather.value?weather.value?.revision:null,expected_facts_revision:state.value.facts_revision,expected_plan_version:state.value.plan_version}));await load();notice.value='完整周期仅为草稿；确认前不进入正式日历。'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function approve(){if(!selected.value)return;busy.value=true;error.value='';try{await api(`/plan-proposals/${selected.value.id}/approve`,json('POST',{expected_plan_version:selected.value.base_version,expected_facts_revision:selected.value.facts_revision}));await load();notice.value='跑步与恢复已共同保存为正式版本；每天训练前仍需核对身体反馈。';emit('changed')}catch(e){error.value=(e as Error).message;await load()}finally{busy.value=false}}
async function reject(){if(!selected.value)return;busy.value=true;error.value='';try{await api(`/plan-proposals/${selected.value.id}/reject`,{method:'POST'});await load();notice.value='已拒绝，原正式版本保留。'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(()=>load().catch(e=>error.value=(e as Error).message));watch(()=>props.refreshToken,()=>load().catch(e=>error.value=(e as Error).message))
</script>
<template><section class="card cycle-panel">
 <div class="sectionhead"><div><h2>能力评估与完整周期</h2><p class="tiny muted">依据实际训练基础，规划跑步课程到比赛及赛后七天；每周按档案次数，跑步至少隔天，跨周也不连续跑</p></div><span class="badge">来源已核对 · 规则未临床审阅</span></div>
 <p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
 <template v-if="ability">
  <div class="capacity"><b>{{statusLabels[ability.status]}}</b><p class="tiny">最近28天公路 {{ability.road_records}} 条 / {{ability.occupied_weeks}} 个有记录的七天窗口；每窗口分钟中位数 {{ability.baseline_week_minutes}}，已记录轻松跑最长 {{ability.longest_easy_minutes}} 分钟。</p><p class="tiny">轻松记录配速中位数 {{ability.observed_easy_pace.median_seconds_per_km===null?'未知':`${Math.floor(ability.observed_easy_pace.median_seconds_per_km/60)}′${String(ability.observed_easy_pace.median_seconds_per_km%60).padStart(2,'0')}″/km`}}（{{ability.observed_easy_pace.sample_count}} 个样本），只是观察值，不是训练配速。</p><p class="tiny muted">{{ability.goal.note}} 单次突破或重复变快都不自动加量。{{ability.reduce?'当前反馈触发两类训练共同减量。':''}}</p></div>
  <ul v-if="ability.blocked_reasons.length" class="error"><li v-for="r in ability.blocked_reasons" :key="r">{{r}}</li></ul>
  <details><summary>评估规则、缺失信息与来源</summary><p v-for="l in ability.limitations" :key="l" class="tiny muted">{{l}}</p><p v-for="s in ability.sources" :key="s.url" class="tiny"><a :href="s.url" target="_blank" rel="noopener">{{s.title}} ↗</a>：{{s.scope}}</p></details>
 </template>
 <p class="tiny muted">先在设置核对比赛目标、医生建议，再保存周期日程。支持从开始日到比赛日最多180天；未来周次必须随新反馈重新评估。当前以轻松跑和较长轻松跑为主；连续训练及中等用力记录充分、身体适合且你主动选择时，可加入受控稳态跑，不安排全力测试或目标配速冲刺；比赛日与赛后保留单独核对事项。</p>
 <label class="field">周期开始日期<input v-model="start" type="date" :min="today" :max="profile?.goal_date||undefined"></label>
 <details class="cycle-schedule"><summary>设置周期内每周可训练时间</summary><p class="tiny muted">勾选你确定可用的星期，分钟由跑步使用；未勾选为不可训练。</p><div v-for="s in slots" :key="s.weekday" class="schedule-slot"><label><input v-model="s.enabled" type="checkbox">{{dayNames[s.weekday]}}</label><label class="field">可用分钟<input v-model.number="s.duration_minutes" type="number" min="10" max="480" :disabled="!s.enabled"></label></div><label class="privacy-check"><input v-model="preserve" type="checkbox">保留日历里已保存的日期例外；取消后才按本次星期覆盖周期范围</label><button class="btn" :disabled="busy||!profile?.goal_date" @click="schedule">保存周期日程</button></details>
 <label v-if="ai?.provider==='deepseek'" class="privacy-check"><input v-model="external" type="checkbox">同意将档案（含身体与医生建议）、最多10次跑步／3次反馈、当前计划、完整周期日程和所选记录的评估摘要发送到DeepSeek。不会发送原图、地图或账号。</label>
 <label class="privacy-check"><input v-model="includeWeather" type="checkbox" :disabled="!weather?.forecast||weather.provider==='disabled'">结合已保存的 {{weather?.location?.name||'城市'}} 天气调整剩余周期：避开雷暴预报时段，仍保持隔天跑；同意把七天内已有小时预报及城市名称随计划资料发送至DeepSeek（本地规则模式不外发）。不会额外请求天气。</label>
 <label v-if="includeWeather" class="privacy-check"><input v-model="avoidRain" type="checkbox">我也希望避开有降水预报的跑步时段。日程不足可少跑，不强行补练。</label>
 <p v-if="includeWeather" class="tiny muted">请先在天气卡刷新预报。草稿将在该预报过期时失效；未覆盖日期天气未知，正式计划仍须逐次复核。</p>
 <label class="privacy-check"><input v-model="controlled" type="checkbox">在证据充分、身体反馈适合且日程足够时，允许每周最多一次受控稳态跑；资料不足时仍不安排。不按目标成绩追速。</label><button class="btn primary" :disabled="busy||!profile?.goal_date||(ai?.provider==='deepseek'&&!external)" @click="generate">{{busy?'处理中…':'生成 / 重新评估剩余周期'}}</button>
 <p v-if="state?.needs_review" class="error">身体、日程或所用天气依据已变化 / 过期，原正式计划需重新评估。先保存当前身体反馈，再生成剩余周期；不追补缺少记录的训练。</p>
 <div class="actions"><button v-for="p in candidates" :key="p.id" class="btn" @click="selected=p;history=null">{{p.start_date}} — {{p.end_date}} · {{p.state==='pending'?'待确认':p.state==='applied'?'已应用':p.state==='rejected'?'已拒绝':'已失效'}}</button><button v-if="current" class="btn" @click="selected=null;history=null">查看当前正式周期</button></div>
 <details v-if="versions.length"><summary>完整周期历史（{{versions.length}} 个版本）</summary><button v-for="v in versions" :key="v.id" class="btn" @click="selected=null;history=v">版本 {{v.version}} · {{v.start_date}} — {{v.end_date}}</button><p class="tiny muted">历史只读保留；恢复训练时依据当前事实重新生成剩余周期，不平移旧负荷。</p></details><div v-if="shown" class="cycle-review"><h3>{{selected?'核对完整周期草稿':history?'历史周期 · 只读':'已确认完整周期'}}</h3><p class="tiny">{{shown.start_date}} — {{shown.end_date}} · {{shown.provider==='deepseek'?'DeepSeek AI 蓝图，经后端排期和校验':'本地保守规则草稿，不是AI推理'}} · {{selected?(proposalLabels[selected.state]||selected.state):`版本 ${history?.version||current?.version}`}}</p><p>{{shown.summary}}</p><details v-if="shown.weather_snapshot"><summary>天气调整依据 · {{shown.weather_snapshot.city}}</summary><p class="tiny">训练时间 {{shown.weather_snapshot.training_time}}（{{shown.weather_snapshot.timezone}}）；获取 {{new Date(shown.weather_snapshot.fetched_at).toLocaleString()}}，有效至 {{new Date(shown.weather_snapshot.expires_at).toLocaleString()}}。<a :href="shown.weather_snapshot.source" target="_blank" rel="noopener">预报来源 ↗</a></p><p v-for="d in shown.weather_snapshot.days" :key="d.date" class="tiny">{{d.date}}：{{d.blocked_reason||(d.window_complete?'已参考训练窗口预报；不等于适跑许可':'部分时段或整日天气未知')}}</p><p v-for="l in shown.weather_snapshot.limitations" :key="l" class="tiny muted">{{l}}</p></details><p class="tiny muted">{{shown.assessment}}</p><p v-for="q in shown.questions" :key="q" class="tiny">需核对：{{q}}</p><details><summary>删减原因与不确定性</summary><p v-for="u in shown.uncertainties" :key="u" class="tiny muted">{{u}}</p></details>
  <details v-for="w in shown.cycle_weeks" :key="w.index" class="cycle-week-review"><summary>{{w.start}} — {{w.end}} · {{phases[w.phase]}} · 跑步 {{total(sessions(w.start,w.end),'run')}} 分钟</summary><p class="tiny muted">阶段跑步上限 {{w.run_minutes_cap}} 分钟、单次 {{w.single_run_minutes_cap}} 分钟；这是产品上限，不是必须完成的目标。</p><article v-for="s in sessions(w.start,w.end)" :key="s.id" class="cycle-session"><b>{{s.date}} · {{types[s.type]}} · {{s.title}}</b><p class="tiny">{{s.duration_minutes?`${s.duration_minutes} 分钟`:'零训练负荷 / 待核对'}} · {{s.purpose}}</p><p v-for="b in s.blocks" :key="b.label" class="tiny">{{b.label}}：{{b.minutes}} 分钟</p><div v-for="e in s.exercises" :key="e.exercise_id"><p class="tiny">{{exercises.find(x=>x.id===e.exercise_id)?.name}} · {{e.sets}}组 × {{e.repetitions}}次 · 休息{{e.rest_seconds}}秒 · {{e.resistance}}</p><p class="tiny muted">{{exercises.find(x=>x.id===e.exercise_id)?.cues}}</p></div><p class="tiny muted">{{s.stop_condition}}</p></article></details>
  <details v-if="selected"><summary>查看逐日原安排 → 新安排</summary><article v-for="c in selected.changes" :key="c.date" class="cycle-session"><b>{{c.date}}</b><p class="tiny">原：{{c.before.map(s=>`${types[s.type]} ${s.duration_minutes}分钟`).join('；')||'无安排'}}</p><p class="tiny">新：{{c.after.map(s=>`${types[s.type]} ${s.duration_minutes}分钟`).join('；')||'不在新周期范围；历史版本仍保留'}}</p><p class="tiny muted">核对背景：{{c.reason}}</p></article></details>
  <p class="tiny muted">{{shown.evidence_ids.length}} 条已保存证据；周期草稿与实际记录分开。确认后可在日历逐日查看。新疼痛、疾病或日程改变使旧提案失效；未来安排不能代替当天身体评估。</p>
  <div v-if="selected" class="actions"><button class="btn primary" :disabled="busy||selected.state!=='pending'" @click="approve">确认跑步与恢复整体更新</button><button class="btn" :disabled="busy||selected.state!=='pending'" @click="reject">拒绝此周期草稿</button></div>
 </div>
</section></template>
<style scoped>
.cycle-panel{margin-top:24px;overflow-wrap:anywhere}.cycle-panel .sectionhead{gap:12px;flex-wrap:wrap}.cycle-panel p{margin:10px 0}.capacity{padding:16px;background:#f3f5ef;border-radius:10px;margin:16px 0}.cycle-panel details{margin:16px 0}.cycle-panel .field{max-width:300px;margin:16px 0}.schedule-slot{display:flex;align-items:center;gap:24px}.schedule-slot .field{margin:6px 0;max-width:160px}.cycle-panel .privacy-check{display:block;line-height:1.8;margin:16px 0;font-size:12px}.cycle-review{margin-top:24px;border-top:1px solid #e5e8df;padding-top:20px}.cycle-session{padding:12px;border-radius:8px;background:#f6f8f3;margin:12px 0}.cycle-week-review{padding:12px;border:1px solid #e5e8df;border-radius:8px}@media(max-width:600px){.cycle-panel .actions{align-items:stretch;flex-direction:column}.cycle-panel .btn{white-space:normal}}
</style>
