<script setup lang="ts">
import {onMounted,ref,watch} from 'vue'
import {api,json} from '../api'
type Settings={enabled:boolean;plan_updates:boolean;training_reminders:boolean;lead_minutes:number;daily_limit:number;quiet_enabled:boolean;quiet_start:string;quiet_end:string;revision:number;timezone:string;attention:string}
type Job={id:string;state:string;title:string;reason:string;attempts:number;due_at:string;expires_at:string;plan_version:number}
const props=defineProps<{refreshToken:number}>()
const settings=ref<Settings|null>(null),jobs=ref<Job[]>([]),busy=ref(false),error=ref(''),notice=ref('')
const labels:Record<string,string>={pending:'待模拟',simulated:'模拟完成 · 未发微信',cancelled:'已取消',failed:'明确失败',unknown:'结果未知 · 不自动重试'}
async function load(){const [s,j]=await Promise.all([api<Settings>('/notification-settings'),api<Job[]>('/notifications')]);settings.value=s;jobs.value=j}
async function save(){if(!settings.value)return;busy.value=true;error.value='';try{const s=settings.value;await api('/notification-settings',json('PUT',{enabled:s.enabled,plan_updates:s.plan_updates,training_reminders:s.training_reminders,lead_minutes:s.lead_minutes,daily_limit:s.daily_limit,quiet_enabled:s.quiet_enabled,quiet_start:s.quiet_start,quiet_end:s.quiet_end,expected_revision:s.revision}));await load();notice.value='本地提醒偏好已保存；尚未启用微信或后台进程。'}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function run(mode:'preview'|'simulate'){busy.value=true;error.value='';try{const r=await api<{simulated_count?:number}>(`/notifications/${mode}`,{method:'POST'});await load();notice.value=mode==='preview'?'已按正式计划核对队列，未发送微信。':`本次完成 ${r.simulated_count||0} 条本地模拟，未发送微信；未到时间的提醒继续等待。`}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
onMounted(()=>load().catch(e=>error.value=(e as Error).message));watch(()=>props.refreshToken,()=>load().catch(e=>error.value=(e as Error).message))
</script>
<template><section class="card panelwide notification-panel"><div class="sectionhead"><h2>训练提醒</h2><span class="badge">本地模拟 · 微信未接通</span></div><p class="tiny muted">只为已确认且仍有效的计划创建提醒，不推送草稿或补催漏练。这里保存偏好、核对队列并模拟处理，不会发微信。后台模拟进程需另外启动。</p><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><form v-if="settings" @submit.prevent="save"><p v-if="settings.attention" class="tiny muted">{{settings.attention}}；当前不创建训练提醒。</p><label class="privacy-check"><input v-model="settings.enabled" type="checkbox">启用本地提醒队列</label><div class="form-grid"><label class="privacy-check"><input v-model="settings.plan_updates" type="checkbox">正式计划更新提醒</label><label class="privacy-check"><input v-model="settings.training_reminders" type="checkbox">训练前核对提醒（按个人档案常用时段）</label><label class="field">提前分钟<input v-model.number="settings.lead_minutes" type="number" min="5" max="180" required></label><label class="field">每天最多几条<input v-model.number="settings.daily_limit" type="number" min="1" max="5" required></label><label class="privacy-check span2"><input v-model="settings.quiet_enabled" type="checkbox">启用免打扰（{{settings.timezone}}）</label><label class="field">免打扰开始<input v-model="settings.quiet_start" type="time" required></label><label class="field">免打扰结束<input v-model="settings.quiet_end" type="time" required></label></div><p class="tiny muted">免打扰期间延期；已到训练时段或依据失效时取消。结果未知时不会自动重试；只有明确失败才限次重试。</p><button class="btn primary" :disabled="busy">保存提醒偏好</button></form><div class="actions"><button class="btn" :disabled="busy" @click="run('preview')">核对待发队列</button><button class="btn" :disabled="busy" @click="run('simulate')">仅本地模拟处理一次</button></div><details><summary>最近提醒记录（{{jobs.length}}）</summary><p v-if="!jobs.length" class="tiny muted">没有提醒记录；未确认计划、关闭提醒或事实待核对时不会生成。</p><article v-for="j in jobs" :key="j.id" class="notification-job"><b>{{j.title}} · {{labels[j.state]||j.state}}</b><p class="tiny">正式版本 {{j.plan_version}} · 处理 {{j.attempts}} 次</p><p class="tiny muted">预计 {{new Date(j.due_at).toLocaleString()}} · 到期 {{new Date(j.expires_at).toLocaleString()}}</p><p class="tiny">{{j.reason||'尚未处理，未发送微信'}}</p></article></details></section></template>
<style scoped>.notification-panel{margin-top:24px;overflow-wrap:anywhere}.notification-panel .sectionhead{gap:12px;flex-wrap:wrap}.notification-panel p{margin:12px 0}.privacy-check{display:block;line-height:1.8;font-size:13px;margin:12px 0}.notification-panel .actions{margin-top:16px;flex-wrap:wrap}.notification-job{padding:12px;background:#f6f8f3;border-radius:8px;margin-top:12px}.notification-panel details{margin-top:18px}@media(max-width:600px){.notification-panel .btn{white-space:normal}}</style>
