<script setup lang="ts">
import {onMounted,ref,watch} from 'vue'
import {api,json,type WeatherData,type WeatherLocation} from '../api'
const props=defineProps<{refreshToken:number;city:string}>()
const emit=defineEmits<{calendar:[]}>()
const state=ref<WeatherData|null>(null),error=ref(''),busy=ref(false),consent=ref(false),query=ref(''),target=ref(''),mode=ref('local'),localResults=ref<WeatherLocation[]>([]),catalogNote=ref(''),catalogSource=ref('')
const labels:Record<string,string>={disabled:'尚未启用',no_location:'请选择城市',unavailable:'尚未获取预报',expired:'预报已过期',missing_hour:'所选时段没有预报',ready:'小时预报'}
async function load(){try{state.value=await api<WeatherData>('/weather'+(target.value?'?target_date='+encodeURIComponent(target.value):''));if(!target.value)target.value=state.value.target_date}catch(e){error.value=(e as Error).message}}
async function act(path:string,method:string,body:Record<string,unknown>){busy.value=true;error.value='';try{state.value=await api<WeatherData>(path,json(method,{...body,expected_revision:state.value?.revision??0}));await load()}catch(e){error.value=(e as Error).message;await load()}finally{busy.value=false}}
async function searchCity(){if(mode.value==='online'){await act('/weather/search','POST',{name:query.value,allow_external_weather:consent.value});return}busy.value=true;error.value='';try{const r=await api<{candidates:WeatherLocation[];scope:string;snapshot_date:string;source:string}>('/weather/cities?q='+encodeURIComponent(query.value));localResults.value=r.candidates;catalogNote.value=`${r.scope} 数据快照 ${r.snapshot_date}`;catalogSource.value=r.source}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
const value=(v:number|null|undefined,unit:string)=>v==null?'未知':`${v}${unit}`
const time=(v:string)=>state.value?new Intl.DateTimeFormat('zh-CN',{timeZone:state.value.display_timezone,dateStyle:'short',timeStyle:'short'}).format(new Date(v)):v
onMounted(load);watch(()=>props.refreshToken,load)
</script>
<template><article class="card weather-card"><div class="sectionhead"><div><h2>跑步天气</h2><p class="tiny muted">{{state?.location?[state.location.name,state.location.admin1,state.location.country].filter(Boolean).join(' · '):'选择城市，查看常用训练时段'}}</p></div><span class="badge">{{state?labels[state.status]:'正在读取'}}</span></div>
<p v-if="error" class="error" role="alert">{{error}}</p>
<p v-if="state?.provider==='disabled'" class="tiny muted">天气接口默认关闭，尚未请求外部服务。启用方法见配置说明；你仍可直接调整训练日程。</p>
<template v-if="state"><label class="field weather-date">查看训练日期<input v-model="target" type="date" @change="load"></label><p class="tiny muted">常用训练时段 {{state.target_time}} · {{state.display_timezone}}（在个人设置修改）。显示该时段对应的小时预报，不是现场观测。</p>
<div v-if="state.selected_hour" class="weather-values" :class="{muted:state.status!=='ready'}"><strong>{{value(state.selected_hour.temperature_2m,'°C')}}</strong><span>体感 {{value(state.selected_hour.apparent_temperature,'°C')}}</span><span>湿度 {{value(state.selected_hour.relative_humidity_2m,'%')}}</span><span>降水概率 {{value(state.selected_hour.precipitation_probability,'%')}}</span><span>小时降水 {{value(state.selected_hour.precipitation,' mm')}}</span><span>风速 {{value(state.selected_hour.wind_speed_10m,' km/h')}}</span><span>预报时刻 {{time(state.selected_hour.time)}}</span></div>
<p v-if="state.status==='expired'" class="notice tiny">旧预报已过期，仅供核对，不作为当前训练建议；请刷新。</p><p v-if="state.status==='missing_hour'" class="tiny muted">所选时段不在缓存预报范围内，不推测天气。</p><p v-if="state.status==='unavailable'" class="tiny muted">尚无天气数据，不填入模拟温度。</p>
<p v-for="a in state.advice" :key="a" class="tiny">{{a}}</p>
<p v-if="state.forecast" class="tiny muted">获取 {{time(state.forecast.fetched_at)}} · 过期 {{time(state.forecast.expires_at)}} · <a :href="state.source" target="_blank" rel="noopener">Open-Meteo 来源 ↗</a></p>
<p class="tiny muted">空气质量与官方预警未接入。天气缺失不表示适合户外跑；身体限制仍优先。预报不自动修改正式计划。</p>
<p v-if="state.location?.location_source" class="tiny muted">地点来源：{{state.location.location_source==='geonames_local'?'GeoNames 本地目录':'Open-Meteo 在线搜索'}} · 城市参考坐标 {{state.location.latitude}}, {{state.location.longitude}}，不是你的精确定位。<a v-if="state.location.source" :href="state.location.source" target="_blank" rel="noopener">核对地点 ↗</a></p>
<details><summary>{{state.location?'更换天气城市 / 刷新':'选择天气城市'}}</summary><label class="field weather-mode">城市查找方式<select v-model="mode"><option value="local">本地目录 · 不联网</option><option value="online" :disabled="state.provider==='disabled'">在线搜索 · 需同意发送</option></select></label><form @submit.prevent="searchCity"><label class="field">搜索天气城市<input v-model="query" :placeholder="city||'城市中文名或拼音，例如杭州'" maxlength="80"></label><button class="btn" :disabled="busy||(mode==='online'&&(!consent||state.provider==='disabled'))">{{mode==='local'?'查询本地城市':'搜索城市'}}</button></form><p v-if="mode==='local'" class="tiny muted">本地查询不发送城市名；城市参考坐标只在你勾选发送说明并点击获取预报后发给天气服务。</p><div class="weather-results"><button v-for="c in (mode==='local'?localResults:state.candidates)" :key="c.id" class="btn" :disabled="busy" @click="act('/weather/location','PUT',{candidate_id:c.id})">{{c.name}} · {{c.admin1}} · {{c.country}}</button></div><p v-if="mode==='local'&&catalogNote" class="tiny muted">{{catalogNote}} · <a :href="catalogSource" target="_blank" rel="noopener">GeoNames / CC BY 4.0 ↗</a></p><label class="privacy-check"><input v-model="consent" type="checkbox">同意将在线搜索的城市名（仅在线搜索时）、所选城市参考坐标发送给 Open-Meteo 获取预报；不发送路线、精确定位、健康资料或账户。每次由我点击请求。</label><button class="btn" :disabled="busy||!consent||!state.location||state.provider==='disabled'" @click="act('/weather/refresh','POST',{allow_external_weather:consent})">{{busy?'处理中…':'获取 / 刷新预报'}}</button><p class="tiny muted">15分钟内复用缓存；有效期2小时。选择不同城市后旧预报清空。地点与档案城市分开保存。</p></details>
</template><div class="actions"><button class="btn" @click="emit('calendar')">因天气调整日程 →</button></div></article></template>
<style scoped>
.weather-card{min-width:0}.weather-date{max-width:250px}.weather-values{display:flex;flex-wrap:wrap;gap:12px;margin:18px 0;font-size:13px}.weather-values strong{font-size:32px;width:100%;font-family:Georgia,serif}.weather-results{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.weather-card details{font-size:13px}.weather-card summary{cursor:pointer}.weather-card form{display:flex;flex-wrap:wrap;align-items:end;gap:10px;margin:15px 0}.weather-card form .field{flex:1;min-width:160px}.weather-card a{color:var(--green)}.weather-card .sectionhead{align-items:start}.weather-card .privacy-check{margin-top:16px}
</style>
